2025-01-06 18:19:15,550 - storage - INFO - loading file to local_storage started ...
2025-01-06 18:19:15,550 - storage - ERROR - DB File not found: movies.json
2025-01-06 18:19:15,550 - storage - INFO - ... loading file to local_storage finished
2025-01-06 18:19:15,550 - storage - INFO - Context Manager started
2025-01-06 18:19:15,550 - movie_app - INFO - New Instance of MovieApp started
2025-01-06 18:19:15,550 - utils - INFO - Printing options menu...
2025-01-06 18:19:15,550 - utils - INFO - ...finished printing options
2025-01-06 18:19:25,948 - movie_app - INFO - Option executed List movies
2025-01-06 18:19:25,949 - storage - INFO - Listing Movies started
2025-01-06 18:19:25,949 - storage - ERROR - MovieApp is empty or not loaded correctly: movies.json
2025-01-06 18:19:25,949 - storage - INFO - ... Listing Movies finished
2025-01-06 18:19:25,949 - utils - INFO - Printing options menu...
2025-01-06 18:19:25,950 - utils - INFO - ...finished printing options
2025-01-06 18:19:52,577 - storage - ERROR - Exception occurred:
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/main.py", line 8, in main
    app.run()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_app.py", line 67, in run
    action = int(input("\n\nWhat do you want to do ?   "))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-06 18:19:52,582 - storage - INFO - Saving local storage to file ...
2025-01-06 18:19:52,582 - storage - INFO - Movie DB saved to file: movies.json
2025-01-06 18:19:52,582 - storage - INFO - Assertion checked: Remote is synced with Local
2025-01-06 18:19:52,582 - storage - INFO - ... saving local_storage to file finished
2025-01-06 18:19:52,582 - storage - INFO - Context Manager exited. DB saved to: movies.json
2025-01-06 18:19:54,396 - storage - INFO - loading file to local_storage started ...
2025-01-06 18:19:54,396 - storage - ERROR - DB File not found: storage\movies.json
2025-01-06 18:19:54,396 - storage - INFO - ... loading file to local_storage finished
2025-01-06 18:19:54,396 - storage - INFO - Context Manager started
2025-01-06 18:19:54,396 - movie_app - INFO - New Instance of MovieApp started
2025-01-06 18:19:54,396 - utils - INFO - Printing options menu...
2025-01-06 18:19:54,396 - utils - INFO - ...finished printing options
2025-01-06 18:19:56,454 - movie_app - INFO - Option executed List movies
2025-01-06 18:19:56,454 - storage - INFO - Listing Movies started
2025-01-06 18:19:56,454 - storage - ERROR - MovieApp is empty or not loaded correctly: storage\movies.json
2025-01-06 18:19:56,454 - storage - INFO - ... Listing Movies finished
2025-01-06 18:19:56,454 - utils - INFO - Printing options menu...
2025-01-06 18:19:56,454 - utils - INFO - ...finished printing options
2025-01-06 18:29:59,868 - storage - ERROR - Exception occurred:
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/main.py", line 8, in main
    storage_json = storage_dir 'movies.json'
            ^^^^^^^^^
  File "/Users/dda/PycharmProjects/MovieMadness/movie_app.py", line 67, in run
    action = int(input("\n\nWhat do you want to do ?   "))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-06 18:29:59,898 - storage - INFO - Saving local storage to file ...
2025-01-06 18:29:59,904 - storage - INFO - Movie DB saved to file: storage\movies.json
2025-01-06 18:29:59,905 - storage - INFO - Assertion checked: Remote is synced with Local
2025-01-06 18:29:59,905 - storage - INFO - ... saving local_storage to file finished
2025-01-06 18:29:59,905 - storage - INFO - Context Manager exited. DB saved to: storage\movies.json
2025-01-06 18:30:00,650 - storage - INFO - loading file to local_storage started ...
2025-01-06 18:30:00,650 - storage - INFO - Database loaded into local
2025-01-06 18:30:00,650 - storage - INFO - ... loading file to local_storage finished
2025-01-06 18:30:00,651 - storage - INFO - Context Manager started
2025-01-06 18:30:00,651 - movie_app - INFO - New Instance of MovieApp started
2025-01-06 18:30:00,651 - utils - INFO - Printing options menu...
2025-01-06 18:30:00,651 - utils - INFO - ...finished printing options
2025-01-06 18:30:03,993 - movie_app - INFO - Option executed List movies
2025-01-06 18:30:03,997 - storage - INFO - Listing Movies started
2025-01-06 18:30:03,997 - utils - INFO - Printing movies...
2025-01-06 18:30:03,998 - utils - INFO - ...finished printing options
2025-01-06 18:30:03,998 - storage - INFO - ... Listing Movies finished
2025-01-06 18:30:03,998 - utils - INFO - Printing options menu...
2025-01-06 18:30:03,998 - utils - INFO - ...finished printing options
2025-01-06 18:30:15,422 - movie_app - INFO - Option executed Update Movie rating
2025-01-06 18:30:15,423 - storage - INFO - Starting update_movie
2025-01-06 18:30:15,424 - utils - INFO - starting check_movie_title ...
2025-01-06 18:30:18,529 - utils - INFO - Movie Title checked for validity Jaws
2025-01-06 18:30:18,530 - utils - INFO - ... Title check finished
2025-01-06 18:30:18,530 - utils - INFO - starting movie_in_db check...
2025-01-06 18:30:18,530 - utils - INFO - Start check movie rating ...
2025-01-06 18:30:20,830 - utils - INFO - Rating checked for validity 5.0
2025-01-06 18:30:20,831 - utils - INFO - ... Rating check finished
2025-01-06 18:30:20,831 - storage - INFO - Film Jaws : rating updated from 8.0 to 5.0
2025-01-06 18:30:20,831 - storage - INFO - Saving local storage to file ...
2025-01-06 18:30:20,839 - storage - INFO - Movie DB saved to file: /Users/dda/PycharmProjects/MovieMadness/storage/movies.json
2025-01-06 18:30:20,840 - storage - INFO - Assertion checked: Remote is synced with Local
2025-01-06 18:30:20,840 - storage - INFO - ... saving local_storage to file finished
2025-01-06 18:30:20,840 - storage - INFO - ... Update Movie finished
2025-01-06 18:30:20,840 - utils - INFO - Printing options menu...
2025-01-06 18:30:20,840 - utils - INFO - ...finished printing options
2025-01-06 18:30:35,098 - storage - ERROR - Exception occurred:
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/main.py", line 15, in main
    app.run()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_app.py", line 67, in run
    action = int(input("\n\nWhat do you want to do ?   "))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-06 18:30:35,104 - storage - INFO - Saving local storage to file ...
2025-01-06 18:30:35,105 - storage - INFO - Movie DB saved to file: /Users/dda/PycharmProjects/MovieMadness/storage/movies.json
2025-01-06 18:30:35,105 - storage - INFO - Assertion checked: Remote is synced with Local
2025-01-06 18:30:35,105 - storage - INFO - ... saving local_storage to file finished
2025-01-06 18:30:35,105 - storage - INFO - Context Manager exited. DB saved to: /Users/dda/PycharmProjects/MovieMadness/storage/movies.json
